### ISSUE TITLE
Serialization / Deserialization

### ISSUE THREAD

**Issue by tommoor** [loggur/redux-replicate-localforage#2] opened 2016-05-02 22:09 UTC
Hey!

So we were having performance problems in our app and I tracked it down to the stringification in redux-replicate-localforage. After looking into localforage it seems as though you don't need to to stringify at all - localforage will take care of that if needed and for IndexedDB it's actually capable of storing native objects.

I've removed this in our local version and it seems to work well and be significantly faster. I wondered if you remembered why this was added? Perhaps it's not needed at all in the module.

**Comment by timbur** [comment] 2016-05-02 23:05
If I recall correctly, I added it because localForage and/or IndexedDB wasn't storing certain types properly - e.g., if states were a custom object/instance, ES6 Map, ES6 Set, etc.  It may be possible to remove the stringification part of it while still supporting custom objects/instances by using the same method during stringification.

Right now I'm in the middle of making some changes which will include the ability to query by value (state).  The changes are small but it will require a major version bump (i.e., it will be v2.0) so I will definitely look into removing the stringification while I'm at it.  After that, everything should hopefully be super stable.  :smile:

If you have any suggestions or questions, please let me know.  👍

**Comment by timbur** [comment] 2016-05-02 23:28
Could the problem actually be that the serialization is happening too often?  What if we add debouncing and/or batched serialization to it?

**Comment by tommoor** [comment] 2016-05-03 00:19
Thanks @timbur I suspected this would be the case - For us I've removed it and we're not using any custom types that can't be serialized so it seems to work well and is *significantly* faster 😄 

I thought about debouncing too, but I think that would introduce a level of unreliability that would be undesirable, for example if the app was quite before the correct state is saved. Perhaps that could be optional..?

**Comment by timbur** [comment] 2016-05-03 00:55
Yeah let's do both!  I think we can use the same algorithms as the serializer for custom objects/instances, and debouncing will be optional.  👍

**Comment by tommoor** [comment] 2016-05-20 16:19
The more we've lived with this, the more we think that debouncing / throttling will be a great addition to this library :) Even without the serialization there is significant overhead to using indexeddb it seems

**Comment by timbur** [comment] 2016-05-20 17:27
Good to know!  😀 

> Right now I'm in the middle of making some changes which will include the ability to query by value (state).
This part is taking a lot longer than expected to get working the way I want, but I think it's well worth it.  Almost finished and then I'll return to this.  👍

**Comment by tommoor** [comment] 2016-06-03 22:27
Okay, so I'm glad we had a delay here - I actually tried adding this in myself and it introduced a whole bunch of weird and wacky behavior as we are querying indexed db directly and the data isn't always there with a throttle.

A better API that achieves what we're after might be some ability to 'flush' the current state to the db - for example we'd do this onbeforeunload of the window. Let me know if you think this would make sense in this lib or not..

**Comment by timbur** [comment] 2016-06-04 01:23
Interesting.  I've *finally* finished the brunt of the query functionality (among a few other things - e.g., fully automatic server (re)rendering) so I should be able to take a closer look at this within the next few days, at the latest.  I'll keep you updated on my progress and please LMK if you've encountered anything else worth sharing!  😄

**Comment by timbur** [comment] 2016-06-12 02:23
@tommoor Can you try out v2.0.0-alpha.2 and let me know if it seems more performant for you?  The stringification is disabled when IndexedDB is detected, and it has a debounce time of 10 milliseconds by default.  [See README for how to configure the debounce.](https://github.com/loggur/redux-replicate-localforage#debouncing)

**Comment by timbur** [comment] 2016-06-23 18:42
How's it going @tommoor ?

**Comment by tommoor** [comment] 2016-06-26 22:12
Hey Tim, sorry for the delay! We actually pulled this module out in favor of saving the state manually only at opportune moments in our app as we're having performance issues in general - for example signin / signout / quit :(

**Comment by timbur** [comment] 2016-06-27 00:21
I see.  That's weird.  I'm curious as to how you have it configured exactly.  Are you saving the entire store each time or something?  Or is each `{ [reducerKey]: state }` (assuming you're using the `reducerKeys` option, which is the best way to go) just enormous?  There should be little to no performance issues unless you're either saving the entire state or if many `{ [reducerKey]: state }` changes occur at once (and often).

**Comment by timbur** [comment] 2016-06-28 17:55
I don't think the issue lies with this library in particular (at least not anymore), so I'm going to close this.  Feel free to continue the discussion or if you can give me a way to reproduce the issue, I'd be glad to reopen it.  👍

**Closed by timbur** 2016-06-28 17:55 UTC

**Comment by tommoor** [comment] 2016-06-28 18:03
Yep, our performance issues are not due to this I don't think - and even if they were our app is probably an outlier ;)
